In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you created in part one into a DataFrame
city_data_df =pd.read_csv("weather_data/cities.csv.")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Sitka,US,2020-05-28 21:28:28,57.05,-135.33,57.2,54,75,11.41
1,1,Ribeira Grande,PT,2020-05-28 21:28:11,38.52,-28.70,62.6,55,20,13.87
2,2,Coquimbo,CL,2020-05-28 21:29:14,-29.95,-71.34,62.6,63,69,9.17
3,3,Cape Town,ZA,2020-05-28 21:27:08,-33.93,18.42,64.0,93,90,16.11
4,4,Ushuaia,AR,2020-05-28 21:28:03,-54.80,-68.30,41.0,56,100,13.87

In [3]:
# Get the data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 32.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind= city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
5,5,Victoria,HK,2020-05-28 21:26:48,22.29,114.16,80.01,88,29,10.00
8,8,Faanui,PF,2020-05-28 21:28:44,-16.48,-151.75,82.06,76,30,14.74
10,10,Barhiya,IN,2020-05-28 21:32:13,25.28,86.03,82.44,68,34,12.57
14,14,Canto Do Buriti,BR,2020-05-28 21:32:14,-8.11,-42.94,75.15,89,81,0.85
16,16,Puerto Ayora,EC,2020-05-28 21:28:12,-0.74,-90.35,84.20,58,75,10.29
17,17,Kapaa,US,2020-05-28 21:27:10,22.08,-159.32,80.60,65,20,12.75
18,18,Kimbe,PG,2020-05-28 21:32:14,-5.55,150.14,80.22,80,6,2.53
23,23,Yaan,NG,2020-05-28 21:29:22,7.38,8.57,78.08,90,100,8.21
25,25,Butaritari,KI,2020-05-28 21:28:17,3.07,172.79,83.05,79,3,12.93
26,26,Rikitea,PF,2020-05-28 21:28:06,-23.12,-134.97,76.82,84,39,7.58

In [12]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp    Lat     Lng Hotel Name
5          Victoria      HK     80.01  22.29  114.16
8            Faanui      PF     82.06 -16.48 -151.75
10          Barhiya      IN     82.44  25.28   86.03
14  Canto Do Buriti      BR     75.15  -8.11  -42.94
16     Puerto Ayora      EC     84.20  -0.74  -90.35
17            Kapaa      US     80.60  22.08 -159.32
18            Kimbe      PG     80.22  -5.55  150.14
23             Yaan      NG     78.08   7.38    8.57
25       Butaritari      KI     83.05   3.07  172.79
26          Rikitea      PF     76.82 -23.12 -134.97

In [16]:
# Import API key
from config import g_key

In [17]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [22]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "hotel name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    
hotel_df

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name,Hotel Duo,Hôtel Duo,hotel name
5,Victoria,HK,80.01,22.29,114.16,Mini Hotel Central,Mini Hotel Central,Mini Hotel Central,Mini Hotel Central
8,Faanui,PF,82.06,-16.48,-151.75,Bora-Bora Pearl Beach Resort & Spa,Bora-Bora Pearl Beach Resort & Spa,Bora-Bora Pearl Beach Resort & Spa,Bora-Bora Pearl Beach Resort & Spa
10,Barhiya,IN,82.44,25.28,86.03,PRINCE ELECTRICAL AND DIGITAL STUDIO,PRINCE ELECTRICAL AND DIGITAL STUDIO,PRINCE ELECTRICAL AND DIGITAL STUDIO,PRINCE ELECTRICAL AND DIGITAL STUDIO
14,Canto Do Buriti,BR,75.15,-8.11,-42.94,Novo Hotel,Novo Hotel,Novo Hotel,Novo Hotel
16,Puerto Ayora,EC,84.20,-0.74,-90.35,Finch Bay Galapagos Hotel,Finch Bay Galapagos Hotel,Finch Bay Galapagos Hotel,Finch Bay Galapagos Hotel
...,...,...,...,...,...,...,...,...,...
538,Itoman,JP,77.00,26.12,127.67,Southern Beach Hotel & Resort Okinawa,NaN,Southern Beach Hotel & Resort Okinawa,Southern Beach Hotel & Resort Okinawa
541,Kandi,BJ,80.33,11.13,2.94,Maison des producteurs kandi,NaN,Maison des producteurs kandi,Maison des producteurs kandi
544,Darbhanga,IN,80.62,26.17,85.90,Arvind and Agarwal Hotel,NaN,Arvind and Agarwal Hotel,Arvind and Agarwal Hotel
553,Majene,ID,77.27,-3.54,118.97,Kost Putri RABBANI,NaN,Kost Putri RABBANI,Kost Putri RABBANI
554,Corralillo,CU,82.45,22.98,-80.59,Hostal De Pedri,NaN,Hostal De Pedri,Hostal De Pedri

In [23]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [26]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [27]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))